# Clean Transform MBS Subsidised Services & Benefits Data

In [130]:
# import libraries
import pandas as pd
import numpy as np
import os

## 1. MBS 2021-2022 Data Cleaning & Tranformation

In [131]:
# import the mbs data files and assign to a dataframe

# setup path to original dataset of mbs fileds
path = r'/Users/patel/Documents/CF-Data Anaylst Course/portfolio_projects/mbs_analysis/datasets/'

#import required columns
filter_cols = ["Worksheet","Year","StateTerritory","GeographicUnit","GeographicCode","GeographicAreaName","GeographicGroup", "ServiceLevel", "Service", "DemographicGroup","MeasureName","MeasureValue","Flag","FlagExplanation"]

df_mbs_2021 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2021-2022/AIHW_MBS_2122_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)
df_mbs_2021.head(3)

/var/folders/6w/mdyngzzd2_z7brmk404qky_m0000gs/T/ipykernel_31094/485236433.py:9: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mbs_2021 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2021-2022/AIHW_MBS_2122_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
0,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Percentage of people who had the service (%),84.14%,NaN,NaN
1,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Services per 100 people,395.16,NaN,NaN
2,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Medicare benefits per 100 people,"17,792.31",NaN,NaN

In [132]:
df_mbs_2021.shape

(364176, 14)

In [133]:
df_mbs_2021.index.name = 'id'
df_mbs_2021.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
id,,,,,,,,,,,,,,
0,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Percentage of people who had the service (%),84.14%,NaN,NaN
1,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Services per 100 people,395.16,NaN,NaN
2,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Medicare benefits per 100 people,"17,792.31",NaN,NaN
3,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,No. of patients,"3,997,279",NaN,NaN
4,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,No. of services,"18,772,343",NaN,NaN

### 1.2 Extract and transform SA3 Worksheet Data

SA3 worksheet contains Medicare subsidsed servicees data by Statistical Area Level 3 (geograpghical area)

In [134]:
# check the worksheet names to find SA3 reference
df_mbs_2021['Worksheet'].unique()

array(['PHN', 'SA3', 'PHN - Age standardised', 'PHN - GP aged care'],
      dtype=object)

In [135]:
df_mbs_2021[df_mbs_2021['Worksheet']=='SA3'].count()

Worksheet             231712
Year                  231712
StateTerritory        227680
GeographicUnit        231712
GeographicCode        231712
GeographicAreaName    231712
GeographicGroup       231712
ServiceLevel          231712
Service               231712
DemographicGroup      231712
MeasureName           231712
MeasureValue          231712
Flag                   16607
FlagExplanation        16607
dtype: int64

In [136]:
# extract SA3 data into a new dataframe
df_mbs_2021_sa3 = df_mbs_2021.loc[df_mbs_2021['Worksheet']=='SA3']
df_mbs_2021_sa3.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
id,,,,,,,,,,,,,,
132192,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),83.76%,NaN,NaN
132193,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Services per 100 people,435.77,NaN,NaN
132194,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Medicare benefits per 100 people,"19,788.53",NaN,NaN
132195,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,No. of patients,"6,578,439",NaN,NaN
132196,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,No. of services,"34,223,467",NaN,NaN

In [137]:
print(df_mbs_2021_sa3.index.name)
df_mbs_2021_sa3.shape

id

(231712, 14)

In [138]:
df_mbs_2021_sa3.isna().sum()

Worksheet                  0
Year                       0
StateTerritory          4032
GeographicUnit             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
ServiceLevel               0
Service                    0
DemographicGroup           0
MeasureName                0
MeasureValue               0
Flag                  215105
FlagExplanation       215105
dtype: int64

In [139]:
df_mbs_2021_sa3[df_mbs_2021_sa3['StateTerritory'].isna()]

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
id,,,,,,,,,,,,,,
132864,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),81.88%,NaN,NaN
132865,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Services per 100 people,434.05,NaN,NaN
132866,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Medicare benefits per 100 people,"19,555.73",NaN,NaN
132867,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,No. of patients,"979,505",NaN,NaN
132868,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,No. of services,"5,192,202",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136891,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,No. of patients,181,NaN,NaN
136892,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,No. of services,460,NaN,NaN
136893,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Total Medicare benefits paid,"$26,965",NaN,NaN
136894,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Total provider fees,"$50,679",NaN,NaN
136895,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Estimated resident population,535932,NaN,NaN

State Terriory had 4,032 blanls because SA3 Group aggregages are not for a specific state or terriorty. They are showing aggregrates of each SA3 group by demographics and service.

SA3 groups:
004-01 = Major cities - higher SES
004-02 = Major cities - medium SES
004-03 = Major cities - lower SES
004-04 = Inner regional
004-05 = Outer regional
004-06 = Remote (incl. very remote)

In [140]:
# to ensure pivot table does not skip the blank stateterritory, filling in the blank cells.
df_mbs_2021_sa3_fill_na = df_mbs_2021_sa3.copy()
df_mbs_2021_sa3_fill_na['StateTerritory'].fillna('National-SA3Group', inplace=True)

In [141]:
print(df_mbs_2021_sa3_fill_na.isna().sum())
df_mbs_2021_sa3_fill_na.shape

Worksheet                  0
Year                       0
StateTerritory             0
GeographicUnit             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
ServiceLevel               0
Service                    0
DemographicGroup           0
MeasureName                0
MeasureValue               0
Flag                  215105
FlagExplanation       215105
dtype: int64

(231712, 14)

In [142]:
# Use pivot_table to reshape the DataFrame
df_mbs_2021_sa3_pivot = df_mbs_2021_sa3_fill_na.pivot_table(index=['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode', 
                                                           'GeographicAreaName', 'GeographicGroup', 'ServiceLevel', 'Service', 'DemographicGroup'],
                            columns='MeasureName', 
                            values='MeasureValue',
                            aggfunc='first')  # 'first' is used to pick the first value in case of duplicates

# Reset index to make the DataFrame flat
df_mbs_2021_sa3_pivot.reset_index(inplace=True)
df_mbs_2021_sa3_pivot.head(5)

MeasureName,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Estimated resident population,Medicare benefits per 100 people,No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid,Total provider fees
0,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,33439,"4,385.95","6,371","16,206",19.05%,48.46,"$1,466,617","$2,259,631"
1,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,34495,"6,177.09","8,921","23,460",25.86%,68.01,"$2,130,787","$3,248,640"
2,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,22397,"6,283.74","9,848","19,883",43.97%,88.78,"$1,407,369","$1,933,615"
3,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,15541,"7,940.67","9,794","21,140",63.02%,136.03,"$1,234,059","$1,594,820"
4,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,105872,"5,892.81","34,933","80,690",33.00%,76.21,"$6,238,832","$9,036,706"

In [143]:
df_mbs_2021_sa3_pivot.isna().sum()

MeasureName
Worksheet                                       0
Year                                            0
StateTerritory                                  0
GeographicUnit                                  0
GeographicCode                                  0
GeographicAreaName                              0
GeographicGroup                                 0
ServiceLevel                                    0
Service                                         0
DemographicGroup                                0
Estimated resident population                   0
Medicare benefits per 100 people                0
No. of patients                                 0
No. of services                                 0
Percentage of people who had the service (%)    0
Services per 100 people                         0
Total Medicare benefits paid                    0
Total provider fees                             0
dtype: int64

In [144]:
#removed the column index 'MeasureValue' to simply the table
df_mbs_2021_sa3_pivot.columns.name = None
df_mbs_2021_sa3_pivot.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Estimated resident population,Medicare benefits per 100 people,No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid,Total provider fees
0,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,33439,"4,385.95","6,371","16,206",19.05%,48.46,"$1,466,617","$2,259,631"
1,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,34495,"6,177.09","8,921","23,460",25.86%,68.01,"$2,130,787","$3,248,640"
2,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,22397,"6,283.74","9,848","19,883",43.97%,88.78,"$1,407,369","$1,933,615"
3,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,15541,"7,940.67","9,794","21,140",63.02%,136.03,"$1,234,059","$1,594,820"
4,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,105872,"5,892.81","34,933","80,690",33.00%,76.21,"$6,238,832","$9,036,706"

In [145]:
# check number of rows and columns as expected
df_mbs_2021_sa3_pivot.shape

(28964, 18)

In [146]:
# counting distinct values. Checking for 'National-SA3Group'
df_mbs_2021_sa3_pivot['StateTerritory'].value_counts()

NSW                  7623
Qld                  6887
Vic                  5543
WA                   2847
SA                   2350
Tas                  1257
ACT                   840
NT                    750
National-SA3Group     504
Other Territories     279
National               84
Name: StateTerritory, dtype: int64

In [147]:
df_mbs_2021_sa3_pivot.to_csv(os.path.join(path, 'clean_datasets/mbs_data/2021-22_phc_mbs.csv'))