## Exporting Data Slices

Script was use to export various dataslieces for additional analysis in Excel and Tableau

In [15]:
import pandas as pd
import os
import numpy as np

pd.set_option("display.max_rows", 40)
pd.set_option("display.max_columns", None)

### Import Datasets

In [16]:
path = r"/Users/patel/Documents/CF-Data Anaylst Course/portfolio_projects/mbs_analysis/datasets/"

df_mbs_sa3_service_1_np = pd.read_pickle(
    os.path.join(
        path, "clean_datasets/2014-22_combined_service_1_categories_no_pivot.pkl"
    )
)
df_mbs_sa3_service_1_np.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103592 entries, 0 to 229389
Data columns (total 52 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Year                            103592 non-null  int64
 1   StateTerritory                  103592 non-null  object
 2   GeographicCode                  103592 non-null  object
 3   GeographicAreaName              103592 non-null  object
 4   GeographicGroup                 103592 non-null  object
 5   ServiceLevel                    103592 non-null  object
 6   Service                         103592 non-null  object
 7   DemographicGroup                103592 non-null  object
 8   MBS_per_100                     103592 non-null  float64
 9   No_of_patients                  103592 non-null  Int32
 10  No_of_services                  103592 non-null  Int64
 11  %_People_had_service            103592 non-null  float64
 12  Services_100_people             103592 non-null  float64
 13  Total_mbs_paid_$                103592 non-null  float64
 14  Total_provider_fees_$           103592 non-null  float64
 15  ERP                             103592 non-null  Int64
 16  key_x                           103592 non-null  object
 17  Out_of_Pocket                   103592 non-null  float64
 18  Out_of_pocket_cost_%            103592 non-null  float64
 19  Out_of_pocket_cost_per_person   103592 non-null  float64
 20  No_of_service_per_person        103592 non-null  float64
 21  Out_of_pocket_cost_per_service  103592 non-null  float64
 22  Patient_ERP_Flag                103592 non-null  bool
 23  negative_income                 103592 non-null  int64
 24  no_income_or_not_applicable     103592 non-null  int64
 25  average_income_$5200            103592 non-null  int64
 26  average_income_$13000           103592 non-null  int64
 27  average_income_$18200           103592 non-null  int64
 28  average_income_$26000           103592 non-null  int64
 29  average_income_$36400           103592 non-null  int64
 30  average_income_$46800           103592 non-null  int64
 31  average_income_$58500           103592 non-null  int64
 32  average_income_$71500           103592 non-null  int64
 33  average_income_$91000           103592 non-null  int64
 34  average_income_$130000          103592 non-null  int64
 35  average_income_$169000+         103592 non-null  int64
 36  Population_demographic          103592 non-null  object
 37  Population                      103592 non-null  int64
 38  %_out_of_pocket_by_$5200        103592 non-null  float64
 39  %_out_of_pocket_by_$13000       103592 non-null  float64
 40  %_out_of_pocket_by_$18200       103592 non-null  float64
 41  %_out_of_pocket_by_$26000       103592 non-null  float64
 42  %_out_of_pocket_by_$36400       103592 non-null  float64
 43  %_out_of_pocket_by_$46800       103592 non-null  float64
 44  %_out_of_pocket_by_$58500       103592 non-null  float64
 45  %_out_of_pocket_by_$71500       103592 non-null  float64
 46  %_out_of_pocket_by_$91000       103592 non-null  float64
 47  %_out_of_pocket_by_$130000      103592 non-null  float64
 48  %_out_of_pocket_by_$169000+     103592 non-null  float64
 49  Cost_Burden                     103592 non-null  object
 50  Service_Usage                   103592 non-null  object
 51  Service_Coverage                103592 non-null  object
dtypes: Int32(1), Int64(2), bool(1), float64(21), int64(15), object(12)
memory usage: 41.1+ MB

In [17]:
df_mbs_sa3_service_1_np["Population_demographic"].value_counts()

All persons    14860
Males          14858
Females        14857
25-44          14802
45-64          14762
65+            14738
0-24           14715
Name: Population_demographic, dtype: int64

In [18]:
df_mbs_sa3_service_1_np.columns

Index(['Year', 'StateTerritory', 'GeographicCode', 'GeographicAreaName',
       'GeographicGroup', 'ServiceLevel', 'Service', 'DemographicGroup',
       'MBS_per_100', 'No_of_patients', 'No_of_services',
       '%_People_had_service', 'Services_100_people', 'Total_mbs_paid_$',
       'Total_provider_fees_$', 'ERP', 'key_x', 'Out_of_Pocket',
       'Out_of_pocket_cost_%', 'Out_of_pocket_cost_per_person',
       'No_of_service_per_person', 'Out_of_pocket_cost_per_service',
       'Patient_ERP_Flag', 'negative_income', 'no_income_or_not_applicable',
       'average_income_$5200', 'average_income_$13000',
       'average_income_$18200', 'average_income_$26000',
       'average_income_$36400', 'average_income_$46800',
       'average_income_$58500', 'average_income_$71500',
       'average_income_$91000', 'average_income_$130000',
       'average_income_$169000+', 'Population_demographic', 'Population',
       '%_out_of_pocket_by_$5200', '%_out_of_pocket_by_$13000',
       '%_out_of_pocket_by_$18200', '%_out_of_pocket_by_$26000',
       '%_out_of_pocket_by_$36400', '%_out_of_pocket_by_$46800',
       '%_out_of_pocket_by_$58500', '%_out_of_pocket_by_$71500',
       '%_out_of_pocket_by_$91000', '%_out_of_pocket_by_$130000',
       '%_out_of_pocket_by_$169000+', 'Cost_Burden', 'Service_Usage',
       'Service_Coverage'],
      dtype='object')

### Import MBS OOP Service Dataset

In [19]:
df_mbs_oop_service = pd.read_pickle(
    os.path.join(path, "clean_datasets/mbs_data/mbs_oop_service_state_year_clean.pkl")
)
df_mbs_oop_service.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 360 entries, 141 to 1255
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    360 non-null    object
 1   Year                     360 non-null    int64
 2   Service                  360 non-null    object
 3   Patient_OOP_per_service  360 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 14.1+ KB

### Combine MBS Census With MBS OOP.

In [20]:
df_mbs_oop_service["State"].unique()

array(['NSW', 'Vic', 'Qld', 'SA', 'WA', 'Tas', 'NT', 'ACT'], dtype=object)

In [21]:
df_mbs_sa3_service_1_np["StateTerritory"].unique()

array(['ACT', 'NSW', 'NT', 'Qld', 'SA', 'Tas', 'Vic', 'WA'], dtype=object)

In [22]:
df_mbs_sa3_service_1_np["Service"].unique()

array(['Allied Health attendances (total)', 'Diagnostic Imaging (total)',
       'GP attendances (total)',
       'Nursing and Aboriginal Health Workers (total)',
       'Specialist attendances (total)'], dtype=object)

In [23]:
df_mbs_oop_service["Service"].unique()

array(['GP attendances (total)',
       'Nursing and Aboriginal Health Workers (total)',
       'Allied Health attendances (total)',
       'Specialist attendances (total)', 'Diagnostic Imaging (total)'],
      dtype=object)

In [24]:
df_mbs_sa3_service_1_np_new = df_mbs_sa3_service_1_np.merge(
    df_mbs_oop_service,
    how="left",
    left_on=["Year", "StateTerritory", "Service"],
    right_on=["Year", "State", "Service"],
)

df_mbs_sa3_service_1_np_new.isnull().sum()

Year                       0
StateTerritory             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
                          ..
Cost_Burden                0
Service_Usage              0
Service_Coverage           0
State                      0
Patient_OOP_per_service    0
Length: 54, dtype: int64

In [25]:
df_mbs_sa3_service_1_np_new.columns

Index(['Year', 'StateTerritory', 'GeographicCode', 'GeographicAreaName',
       'GeographicGroup', 'ServiceLevel', 'Service', 'DemographicGroup',
       'MBS_per_100', 'No_of_patients', 'No_of_services',
       '%_People_had_service', 'Services_100_people', 'Total_mbs_paid_$',
       'Total_provider_fees_$', 'ERP', 'key_x', 'Out_of_Pocket',
       'Out_of_pocket_cost_%', 'Out_of_pocket_cost_per_person',
       'No_of_service_per_person', 'Out_of_pocket_cost_per_service',
       'Patient_ERP_Flag', 'negative_income', 'no_income_or_not_applicable',
       'average_income_$5200', 'average_income_$13000',
       'average_income_$18200', 'average_income_$26000',
       'average_income_$36400', 'average_income_$46800',
       'average_income_$58500', 'average_income_$71500',
       'average_income_$91000', 'average_income_$130000',
       'average_income_$169000+', 'Population_demographic', 'Population',
       '%_out_of_pocket_by_$5200', '%_out_of_pocket_by_$13000',
       '%_out_of_pocket_by_$18200', '%_out_of_pocket_by_$26000',
       '%_out_of_pocket_by_$36400', '%_out_of_pocket_by_$46800',
       '%_out_of_pocket_by_$58500', '%_out_of_pocket_by_$71500',
       '%_out_of_pocket_by_$91000', '%_out_of_pocket_by_$130000',
       '%_out_of_pocket_by_$169000+', 'Cost_Burden', 'Service_Usage',
       'Service_Coverage', 'State', 'Patient_OOP_per_service'],
      dtype='object')

In [26]:
# calculate oop per person annually.

df_mbs_sa3_service_1_np_new["OOP_per_person_annual"] = (
    df_mbs_sa3_service_1_np_new["No_of_service_per_person"]
    * df_mbs_sa3_service_1_np_new["Patient_OOP_per_service"]
)

In [27]:
df_mbs_sa3_service_1_np_exp = df_mbs_sa3_service_1_np_new[
    [
        "Year",
        "StateTerritory",
        "GeographicCode",
        "GeographicAreaName",
        "GeographicGroup",
        "Service",
        "DemographicGroup",
        "MBS_per_100",
        "No_of_patients",
        "No_of_services",
        "%_People_had_service",
        "Services_100_people",
        "Total_mbs_paid_$",
        "Total_provider_fees_$",
        "ERP",
        "Out_of_Pocket",
        "Out_of_pocket_cost_%",
        "Patient_OOP_per_service",
        "No_of_service_per_person",
        "OOP_per_person_annual",
        "negative_income",
        "no_income_or_not_applicable",
        "average_income_$5200",
        "average_income_$13000",
        "average_income_$18200",
        "average_income_$26000",
        "average_income_$36400",
        "average_income_$46800",
        "average_income_$58500",
        "average_income_$71500",
        "average_income_$91000",
        "average_income_$130000",
        "average_income_$169000+",
        "Population",
        "Service_Usage",
        "Service_Coverage",
    ]
]

In [28]:
# exporting MBS-Census-State-Year-Service Level 1 (No demographic Data)
df_mbs_sa3_service_1_np_exp.to_csv(
    os.path.join(
        path, "clean_datasets/cleaned_csv/mbs_sa3_service_1_categories_oop.csv"
    )
)

## State-Year MBS Data by Gender

In [81]:
df_mbs_sa3_gender = df_mbs_sa3_service_1_np_new[
    df_mbs_sa3_service_1_np_new["DemographicGroup"].isin(["Males", "Females"])
]
df_mbs_sa3_gender.shape

(29715, 54)

In [82]:
df_mbs_sa3_gender_state = df_mbs_sa3_gender.groupby(
    by=["Year", "StateTerritory", "Service", "DemographicGroup"], as_index=False
).agg(
    {
        "No_of_patients": "sum",
        "No_of_services": "sum",
        "Total_mbs_paid_$": "sum",
        "Total_provider_fees_$": "sum",
        "ERP": "sum",
        "Patient_OOP_per_service": "mean",
    }
)
df_mbs_sa3_gender_state

,Year,StateTerritory,Service,DemographicGroup,No_of_patients,No_of_services,Total_mbs_paid_$,Total_provider_fees_$,ERP,Patient_OOP_per_service
0,2014,ACT,Allied Health attendances (total),Females,62252,118779,8384876.0,10326728.0,180388,48.84
1,2014,ACT,Allied Health attendances (total),Males,43186,73376,4992689.0,5981999.0,178263,48.84
2,2014,ACT,Diagnostic Imaging (total),Females,65437,149416,18213343.0,25456047.0,180388,107.76
3,2014,ACT,Diagnostic Imaging (total),Males,42704,85077,11829864.0,15140564.0,178263,107.76
4,2014,ACT,GP attendances (total),Females,162985,943789,43097542.0,58052404.0,180388,36.18
...,...,...,...,...,...,...,...,...,...,...
715,2022,WA,GP attendances (total),Males,1170330,7689233,366405018.0,410156938.0,1376477,42.65
716,2022,WA,Nursing and Aboriginal Health Workers (total),Females,157781,387070,10944618.0,12585735.0,1373387,7.74
717,2022,WA,Nursing and Aboriginal Health Workers (total),Males,113162,226467,4466057.0,5043581.0,1376477,7.74
718,2022,WA,Specialist attendances (total),Females,388240,1082965,94179555.0,166710104.0,1350358,99.18
719,2022,WA,Specialist attendances (total),Males,332169,897982,76669224.0,136765662.0,1351848,99.18

In [83]:
# Calculate additional variable to understand state level mbs datapoints
df_mbs_sa3_gender_state["%_People_had_service"] = (
    df_mbs_sa3_gender_state["No_of_patients"] / df_mbs_sa3_gender_state["ERP"] * 100
)
df_mbs_sa3_gender_state["Out_of_Pocket"] = (
    df_mbs_sa3_gender_state["Total_provider_fees_$"]
    - df_mbs_sa3_gender_state["Total_mbs_paid_$"]
)
df_mbs_sa3_gender_state["No_of_service_per_person"] = (
    df_mbs_sa3_gender_state["No_of_services"]
    / df_mbs_sa3_gender_state["No_of_patients"]
)
df_mbs_sa3_gender_state["OOP_per_person_annual"] = (
    df_mbs_sa3_gender_state["No_of_service_per_person"]
    * df_mbs_sa3_gender_state["Patient_OOP_per_service"]
)
df_mbs_sa3_gender_state["Total_Provider_pp_per_service"] = df_mbs_sa3_gender_state[
    "Total_provider_fees_$"
] / (
    df_mbs_sa3_gender_state["No_of_patients"]
    * df_mbs_sa3_gender_state["No_of_service_per_person"]
)
df_mbs_sa3_gender_state["MBS_Rebate_pp_per_service"] = df_mbs_sa3_gender_state[
    "Total_mbs_paid_$"
] / (
    df_mbs_sa3_gender_state["No_of_patients"]
    * df_mbs_sa3_gender_state["No_of_service_per_person"]
)

df_mbs_sa3_gender_state.head(10)

,Year,StateTerritory,Service,DemographicGroup,No_of_patients,No_of_services,Total_mbs_paid_$,Total_provider_fees_$,ERP,Patient_OOP_per_service,%_People_had_service,Out_of_Pocket,No_of_service_per_person,OOP_per_person_annual,Total_Provider_pp_per_service,MBS_Rebate_pp_per_service
0,2014,ACT,Allied Health attendances (total),Females,62252,118779,8384876.0,10326728.0,180388,48.84,34.510056,1941852.0,1.908035,93.188433,86.940688,70.592243
1,2014,ACT,Allied Health attendances (total),Males,43186,73376,4992689.0,5981999.0,178263,48.84,24.226003,989310.0,1.699069,82.982537,81.525281,68.042534
2,2014,ACT,Diagnostic Imaging (total),Females,65437,149416,18213343.0,25456047.0,180388,107.76,36.275695,7242704.0,2.283357,246.054498,170.370288,121.896872
3,2014,ACT,Diagnostic Imaging (total),Males,42704,85077,11829864.0,15140564.0,178263,107.76,23.955616,3310700.0,1.992249,214.684749,177.963069,139.048909
4,2014,ACT,GP attendances (total),Females,162985,943789,43097542.0,58052404.0,180388,36.18,90.352462,14954862.0,5.790649,209.505697,61.509939,45.664383
5,2014,ACT,GP attendances (total),Males,138771,657560,29308427.0,38762072.0,178263,36.18,77.846216,9453645.0,4.738454,171.437266,58.948342,44.571487
6,2014,ACT,Nursing and Aboriginal Health Workers (total),Females,3236,5707,154251.0,156243.0,179903,5.77,1.798747,1992.0,1.763597,10.175955,27.377431,27.028386
7,2014,ACT,Nursing and Aboriginal Health Workers (total),Males,2360,3876,94782.0,97461.0,177236,5.77,1.331558,2679.0,1.642373,9.476492,25.144737,24.45356
8,2014,ACT,Specialist attendances (total),Females,52544,141913,11996339.0,19184915.0,180388,74.40,29.128323,7188576.0,2.700841,200.942585,135.187862,84.533052
9,2014,ACT,Specialist attendances (total),Males,39337,101079,8451509.0,13474790.0,178263,74.40,22.066834,5023281.0,2.569566,191.175677,133.309491,83.612907

In [84]:
# exporting MBS-Census-State-Year-Service Level 1 (No demographic Data)
df_mbs_sa3_gender_state.to_csv(
    os.path.join(
        path, "clean_datasets/cleaned_csv/mbs_census_state_year_service_1_gender.csv"
    )
)

## State-Year MBS Data by Age Groups

In [85]:
df_mbs_sa3_service_1_np_new["DemographicGroup"].unique()

array(['0-24', '25-44', '45-64', '65+', 'All persons', 'Females', 'Males'],
      dtype=object)

In [86]:
df_mbs_sa3_age_group = df_mbs_sa3_service_1_np_new[
    df_mbs_sa3_service_1_np_new["DemographicGroup"].isin(
        ["0-24", "25-44", "45-64", "65+"]
    )
]
df_mbs_sa3_age_group.shape

(59017, 54)

In [87]:
df_mbs_agegroup_state = df_mbs_sa3_age_group.groupby(
    by=["Year", "StateTerritory", "Service", "DemographicGroup"], as_index=False
).agg(
    {
        "No_of_patients": "sum",
        "No_of_services": "sum",
        "Total_mbs_paid_$": "sum",
        "Total_provider_fees_$": "sum",
        "ERP": "sum",
        "Patient_OOP_per_service": "mean",
    }
)
df_mbs_agegroup_state

,Year,StateTerritory,Service,DemographicGroup,No_of_patients,No_of_services,Total_mbs_paid_$,Total_provider_fees_$,ERP,Patient_OOP_per_service
0,2014,ACT,Allied Health attendances (total),0-24,21807,41507,3184886.0,3929983.0,120971,48.84
1,2014,ACT,Allied Health attendances (total),25-44,28286,55789,4354228.0,5576400.0,115568,48.84
2,2014,ACT,Allied Health attendances (total),45-64,34556,57758,3790973.0,4485636.0,82817,48.84
3,2014,ACT,Allied Health attendances (total),65+,20450,36523,2011207.0,2275128.0,38643,48.84
4,2014,ACT,Diagnostic Imaging (total),0-24,20860,34082,3130146.0,4203021.0,120971,107.76
...,...,...,...,...,...,...,...,...,...,...
1435,2022,WA,Nursing and Aboriginal Health Workers (total),65+,116510,294434,5658263.0,5878355.0,430017,7.74
1436,2022,WA,Specialist attendances (total),0-24,125981,272731,28488830.0,54901822.0,818891,99.18
1437,2022,WA,Specialist attendances (total),25-44,155675,378019,35185337.0,65860701.0,766858,99.18
1438,2022,WA,Specialist attendances (total),45-64,204558,547710,45290930.0,83153695.0,669185,99.18
1439,2022,WA,Specialist attendances (total),65+,232346,778889,61547508.0,98951842.0,425541,99.18

In [88]:
# Calculate additional variable to understand state level mbs datapoints
df_mbs_agegroup_state["%_People_had_service"] = (
    df_mbs_agegroup_state["No_of_patients"] / df_mbs_agegroup_state["ERP"] * 100
)
df_mbs_agegroup_state["Out_of_Pocket"] = (
    df_mbs_agegroup_state["Total_provider_fees_$"]
    - df_mbs_agegroup_state["Total_mbs_paid_$"]
)

df_mbs_agegroup_state["No_of_service_per_person"] = (
    df_mbs_agegroup_state["No_of_services"] / df_mbs_agegroup_state["No_of_patients"]
)
df_mbs_sa3_gender_state["OOP_per_person_annual"] = (
    df_mbs_sa3_gender_state["No_of_service_per_person"]
    * df_mbs_sa3_gender_state["Patient_OOP_per_service"]
)
df_mbs_agegroup_state["Total_Provider_pp_per_service"] = df_mbs_agegroup_state[
    "Total_provider_fees_$"
] / (
    df_mbs_agegroup_state["No_of_patients"]
    * df_mbs_agegroup_state["No_of_service_per_person"]
)
df_mbs_agegroup_state["MBS_Rebate_pp_per_service"] = df_mbs_agegroup_state[
    "Total_mbs_paid_$"
] / (
    df_mbs_agegroup_state["No_of_patients"]
    * df_mbs_agegroup_state["No_of_service_per_person"]
)

df_mbs_agegroup_state.head(10)

,Year,StateTerritory,Service,DemographicGroup,No_of_patients,No_of_services,Total_mbs_paid_$,Total_provider_fees_$,ERP,Patient_OOP_per_service,%_People_had_service,Out_of_Pocket,No_of_service_per_person,Total_Provider_pp_per_service,MBS_Rebate_pp_per_service
0,2014,ACT,Allied Health attendances (total),0-24,21807,41507,3184886.0,3929983.0,120971,48.84,18.026634,745097.0,1.90338,94.682415,76.731298
1,2014,ACT,Allied Health attendances (total),25-44,28286,55789,4354228.0,5576400.0,115568,48.84,24.475633,1222172.0,1.972318,99.955188,78.048146
2,2014,ACT,Allied Health attendances (total),45-64,34556,57758,3790973.0,4485636.0,82817,48.84,41.725733,694663.0,1.671432,77.662592,65.635462
3,2014,ACT,Allied Health attendances (total),65+,20450,36523,2011207.0,2275128.0,38643,48.84,52.920322,263921.0,1.785966,62.293021,55.066862
4,2014,ACT,Diagnostic Imaging (total),0-24,20860,34082,3130146.0,4203021.0,120971,107.76,17.243802,1072875.0,1.633845,123.320844,91.841617
5,2014,ACT,Diagnostic Imaging (total),25-44,33933,69288,7779643.0,11926918.0,115568,107.76,29.361934,4147275.0,2.041906,172.135406,112.279803
6,2014,ACT,Diagnostic Imaging (total),45-64,31399,70403,9784755.0,13927712.0,82817,107.76,37.913713,4142957.0,2.242205,197.828388,138.982075
7,2014,ACT,Diagnostic Imaging (total),65+,21554,59747,9203843.0,10357071.0,38643,107.76,55.777243,1153228.0,2.771968,173.348804,154.046948
8,2014,ACT,GP attendances (total),0-24,92926,394912,16652667.0,21198854.0,120971,36.18,76.816758,4546187.0,4.249747,53.679944,42.168045
9,2014,ACT,GP attendances (total),25-44,92766,450128,19756887.0,27829378.0,115568,36.18,80.269625,8072491.0,4.852295,61.825476,43.891709

In [89]:
# exporting MBS-Census-State-Year-Service Level 1 (No demographic Data)
df_mbs_agegroup_state.to_csv(
    os.path.join(
        path, "clean_datasets/cleaned_csv/mbs_census_state_year_service_1_agegroup.csv"
    )
)