# Clean Transform MBS Subsidised Services & Benefits Data

The script loads MBS datasets 2013-19, 2019-21 and 2021-22 and transforms each set to have measure values as separate columns instead of rows. The each dataset is exported to csv file.

In [69]:
# import libraries
import pandas as pd
import numpy as np
import os

## 1.MBS 2021-2022 Data Cleaning & Tranformation

In [70]:
# import the mbs data files and assign to a dataframe

# setup path to original dataset of mbs fileds
path = r'/Users/patel/Documents/CF-Data Anaylst Course/portfolio_projects/mbs_analysis/datasets/'

#import required columns
filter_cols = ["Worksheet","Year","StateTerritory","GeographicUnit","GeographicCode","GeographicAreaName","GeographicGroup", "ServiceLevel", "Service", "DemographicGroup","MeasureName","MeasureValue","Flag","FlagExplanation"]

df_mbs_2021 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2021-2022/AIHW_MBS_2122_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)
df_mbs_2021.head(3)

/var/folders/6w/mdyngzzd2_z7brmk404qky_m0000gs/T/ipykernel_70532/485236433.py:9: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mbs_2021 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2021-2022/AIHW_MBS_2122_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
0,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Percentage of people who had the service (%),84.14%,NaN,NaN
1,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Services per 100 people,395.16,NaN,NaN
2,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Medicare benefits per 100 people,"17,792.31",NaN,NaN

In [71]:
df_mbs_2021.shape

(364176, 14)

In [72]:
df_mbs_2021.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
0,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Percentage of people who had the service (%),84.14%,NaN,NaN
1,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Services per 100 people,395.16,NaN,NaN
2,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Medicare benefits per 100 people,"17,792.31",NaN,NaN
3,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,No. of patients,"3,997,279",NaN,NaN
4,PHN,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,No. of services,"18,772,343",NaN,NaN

### 1.2 Extract and transform SA3 Worksheet Data

SA3 worksheet contains Medicare subsidsed servicees data by Statistical Area Level 3 (geograpghical area)

In [73]:
# check the worksheet names to find SA3 reference
df_mbs_2021['Worksheet'].unique()

array(['PHN', 'SA3', 'PHN - Age standardised', 'PHN - GP aged care'],
      dtype=object)

In [74]:
df_mbs_2021[df_mbs_2021['Worksheet']=='SA3'].count()

Worksheet             231712
Year                  231712
StateTerritory        227680
GeographicUnit        231712
GeographicCode        231712
GeographicAreaName    231712
GeographicGroup       231712
ServiceLevel          231712
Service               231712
DemographicGroup      231712
MeasureName           231712
MeasureValue          231712
Flag                   16607
FlagExplanation        16607
dtype: int64

In [75]:
# extract SA3 data into a new dataframe. Used the copy function so the original dataframe is not impacted.
df_mbs_2021_sa3 = df_mbs_2021.loc[df_mbs_2021['Worksheet']=='SA3'].copy()
df_mbs_2021_sa3.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
132192,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),83.76%,NaN,NaN
132193,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Services per 100 people,435.77,NaN,NaN
132194,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Medicare benefits per 100 people,"19,788.53",NaN,NaN
132195,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,No. of patients,"6,578,439",NaN,NaN
132196,SA3,2021-22,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,No. of services,"34,223,467",NaN,NaN

In [76]:
print(df_mbs_2021_sa3.index.name)
df_mbs_2021_sa3.shape

None

(231712, 14)

In [77]:
df_mbs_2021_sa3.isna().sum()

Worksheet                  0
Year                       0
StateTerritory          4032
GeographicUnit             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
ServiceLevel               0
Service                    0
DemographicGroup           0
MeasureName                0
MeasureValue               0
Flag                  215105
FlagExplanation       215105
dtype: int64

In [78]:
df_mbs_2021_sa3[df_mbs_2021_sa3['StateTerritory'].isna()]

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
132864,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),81.88%,NaN,NaN
132865,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Services per 100 people,434.05,NaN,NaN
132866,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Medicare benefits per 100 people,"19,555.73",NaN,NaN
132867,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,No. of patients,"979,505",NaN,NaN
132868,SA3,2021-22,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,No. of services,"5,192,202",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136891,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,No. of patients,181,NaN,NaN
136892,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,No. of services,460,NaN,NaN
136893,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Total Medicare benefits paid,"$26,965",NaN,NaN
136894,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Total provider fees,"$50,679",NaN,NaN
136895,SA3,2021-22,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Estimated resident population,535932,NaN,NaN

State Terriory had 4,032 blanls because SA3 Group aggregages are not for a specific state or terriorty. They are showing aggregrates of each SA3 group by demographics and service.

SA3 groups:
004-01 = Major cities - higher SES
004-02 = Major cities - medium SES
004-03 = Major cities - lower SES
004-04 = Inner regional
004-05 = Outer regional
004-06 = Remote (incl. very remote)

In [79]:
# to ensure pivot table does not skip the blank stateterritory, filling in the blank cells.
df_mbs_2021_sa3_fill_na = df_mbs_2021_sa3.copy()
df_mbs_2021_sa3_fill_na['StateTerritory'].fillna('National-SA3Group', inplace=True)

In [80]:
print(df_mbs_2021_sa3_fill_na.isna().sum())
df_mbs_2021_sa3_fill_na.shape

Worksheet                  0
Year                       0
StateTerritory             0
GeographicUnit             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
ServiceLevel               0
Service                    0
DemographicGroup           0
MeasureName                0
MeasureValue               0
Flag                  215105
FlagExplanation       215105
dtype: int64

(231712, 14)

In [81]:
# Use pivot_table to reshape the DataFrame
df_mbs_2021_sa3_pivot = df_mbs_2021_sa3_fill_na.pivot_table(index=['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode', 
                                                           'GeographicAreaName', 'GeographicGroup', 'ServiceLevel', 'Service', 'DemographicGroup'],
                            columns='MeasureName', 
                            values='MeasureValue',
                            aggfunc='first')  # 'first' is used to pick the first value in case of duplicates

# Reset index to make the DataFrame flat
df_mbs_2021_sa3_pivot.reset_index(inplace=True)
df_mbs_2021_sa3_pivot.head(5)

MeasureName,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Estimated resident population,Medicare benefits per 100 people,No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid,Total provider fees
0,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,33439,"4,385.95","6,371","16,206",19.05%,48.46,"$1,466,617","$2,259,631"
1,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,34495,"6,177.09","8,921","23,460",25.86%,68.01,"$2,130,787","$3,248,640"
2,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,22397,"6,283.74","9,848","19,883",43.97%,88.78,"$1,407,369","$1,933,615"
3,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,15541,"7,940.67","9,794","21,140",63.02%,136.03,"$1,234,059","$1,594,820"
4,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,105872,"5,892.81","34,933","80,690",33.00%,76.21,"$6,238,832","$9,036,706"

In [82]:
df_mbs_2021_sa3_pivot.shape

(28964, 18)

In [83]:
df_mbs_2021_sa3_pivot.isna().sum()

MeasureName
Worksheet                                       0
Year                                            0
StateTerritory                                  0
GeographicUnit                                  0
GeographicCode                                  0
GeographicAreaName                              0
GeographicGroup                                 0
ServiceLevel                                    0
Service                                         0
DemographicGroup                                0
Estimated resident population                   0
Medicare benefits per 100 people                0
No. of patients                                 0
No. of services                                 0
Percentage of people who had the service (%)    0
Services per 100 people                         0
Total Medicare benefits paid                    0
Total provider fees                             0
dtype: int64

In [84]:
#removed the column index 'MeasureValue' to simply the table
df_mbs_2021_sa3_pivot.columns.name = None
df_mbs_2021_sa3_pivot.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Estimated resident population,Medicare benefits per 100 people,No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid,Total provider fees
0,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,33439,"4,385.95","6,371","16,206",19.05%,48.46,"$1,466,617","$2,259,631"
1,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,34495,"6,177.09","8,921","23,460",25.86%,68.01,"$2,130,787","$3,248,640"
2,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,22397,"6,283.74","9,848","19,883",43.97%,88.78,"$1,407,369","$1,933,615"
3,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,15541,"7,940.67","9,794","21,140",63.02%,136.03,"$1,234,059","$1,594,820"
4,SA3,2021-22,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,105872,"5,892.81","34,933","80,690",33.00%,76.21,"$6,238,832","$9,036,706"

In [85]:
# check number of rows and columns as expected
df_mbs_2021_sa3_pivot.shape

(28964, 18)

In [86]:
# counting distinct values. Checking for 'National-SA3Group'
df_mbs_2021_sa3_pivot['StateTerritory'].value_counts()

NSW                  7623
Qld                  6887
Vic                  5543
WA                   2847
SA                   2350
Tas                  1257
ACT                   840
NT                    750
National-SA3Group     504
Other Territories     279
National               84
Name: StateTerritory, dtype: int64

In [87]:
df_mbs_2021_sa3_pivot.rename(columns={'Medicare benefits per 100 people': 'Medicare benefits per 100 people ($)',
                                       'Total Medicare benefits paid':'Total Medicare benefits paid ($)', 'Total provider fees':'Total provider fees ($)'}, inplace=True)
df_mbs_2021_sa3_pivot.columns

Index(['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit',
       'GeographicCode', 'GeographicAreaName', 'GeographicGroup',
       'ServiceLevel', 'Service', 'DemographicGroup',
       'Estimated resident population', 'Medicare benefits per 100 people ($)',
       'No. of patients', 'No. of services',
       'Percentage of people who had the service (%)',
       'Services per 100 people', 'Total Medicare benefits paid ($)',
       'Total provider fees ($)'],
      dtype='object')

In [88]:
df_mbs_2021_sa3_pivot.drop('Worksheet', axis=1,inplace=True)

In [89]:
df_mbs_2021_sa3_pivot.columns

Index(['Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode',
       'GeographicAreaName', 'GeographicGroup', 'ServiceLevel', 'Service',
       'DemographicGroup', 'Estimated resident population',
       'Medicare benefits per 100 people ($)', 'No. of patients',
       'No. of services', 'Percentage of people who had the service (%)',
       'Services per 100 people', 'Total Medicare benefits paid ($)',
       'Total provider fees ($)'],
      dtype='object')

In [90]:
df_mbs_2021_sa3_pivot.to_csv(os.path.join(path, 'clean_datasets/mbs_data/2021-22_phc_mbs.csv'))

## 2.MBS 2019-2021 Data Cleaning & Tranformation

In [91]:
# import the mbs data files and assign to a dataframe

#import required columns
filter_cols = ["Worksheet","Year","StateTerritory","GeographicUnit","GeographicCode","GeographicAreaName","GeographicGroup", "ServiceLevel", "Service", "DemographicGroup","MeasureName","MeasureValue","Flag","FlagExplanation"]

df_mbs_201921 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2019-2021/AIHW_MBS_1920_2021_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)
df_mbs_201921.head(3)

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
0,PHN,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Percentage of people who had the service (%),85.57,NaN,NaN
1,PHN,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),15-24,Percentage of people who had the service (%),75.21,NaN,NaN
2,PHN,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),25-44,Percentage of people who had the service (%),82.54,NaN,NaN

In [92]:
df_mbs_201921.shape

(628437, 14)

In [93]:
# check the worksheet names to find SA3 reference
df_mbs_201921['Worksheet'].unique()

array(['PHN', 'SA3', 'PHN - Age standardised', 'PHN - GP aged care'],
      dtype=object)

In [94]:
# check for expected rows for SA3
df_mbs_201921[df_mbs_201921['Worksheet']== 'SA3'].count()

Worksheet             400841
Year                  400841
StateTerritory        393869
GeographicUnit        400841
GeographicCode        400841
GeographicAreaName    400841
GeographicGroup       400841
ServiceLevel          400841
Service               400841
DemographicGroup      400841
MeasureName           400841
MeasureValue          400841
Flag                   27993
FlagExplanation        27993
dtype: int64

6972 values are missing for StateTerritory.

### 2.1 Extract and Transform SA3 Worksheet Data

In [95]:
df_mbs_201921_sa3 = df_mbs_201921[df_mbs_201921['Worksheet']== 'SA3'].copy()
df_mbs_201921_sa3

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
113526,SA3,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),81.36,NaN,NaN
113527,SA3,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),25-44,Percentage of people who had the service (%),82.54,NaN,NaN
113528,SA3,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),45-64,Percentage of people who had the service (%),91.83,NaN,NaN
113529,SA3,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),65+,Percentage of people who had the service (%),100,#,The number of Medicare patients is higher than...
113530,SA3,2019-20,National,NAT,001NAT,National,National,Level 1,GP attendances (total),All persons,Percentage of people who had the service (%),87.44,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628160,SA3,2020-21,Other Territories,SA3,90104,Norfolk Island,Remote (incl. very remote),Level 3,Physiotherapy,All persons,Total provider fees ($),n.p.,n.p.,Not published
628161,SA3,2020-21,Other Territories,SA3,90104,Norfolk Island,Remote (incl. very remote),Level 3,Podiatry,All persons,Total provider fees ($),n.p.,n.p.,Not published
628162,SA3,2020-21,Other Territories,SA3,90104,Norfolk Island,Remote (incl. very remote),Level 3,Practice Nurse/Aboriginal Health Worker,All persons,Total provider fees ($),n.p.,n.p.,Not published
628163,SA3,2020-21,Other Territories,SA3,90104,Norfolk Island,Remote (incl. very remote),Level 3,Psychiatry,All persons,Total provider fees ($),n.p.,n.p.,Not published
628164,SA3,2020-21,Other Territories,SA3,90104,Norfolk Island,Remote (incl. very remote),Level 3,Speech Pathology,All persons,Total provider fees ($),n.p.,n.p.,Not published

In [96]:
print(df_mbs_201921_sa3.index.name)
df_mbs_201921_sa3.shape

None

(400841, 14)

In [97]:
df_mbs_201921_sa3.isna().sum()

Worksheet                  0
Year                       0
StateTerritory          6972
GeographicUnit             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
ServiceLevel               0
Service                    0
DemographicGroup           0
MeasureName                0
MeasureValue               0
Flag                  372848
FlagExplanation       372848
dtype: int64

In [98]:
df_mbs_201921_sa3[df_mbs_201921_sa3['StateTerritory'].isna()]

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
113609,SA3,2019-20,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),74.41,NaN,NaN
113610,SA3,2019-20,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),25-44,Percentage of people who had the service (%),74.46,NaN,NaN
113611,SA3,2019-20,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),45-64,Percentage of people who had the service (%),91.81,NaN,NaN
113612,SA3,2019-20,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),65+,Percentage of people who had the service (%),100,#,The number of Medicare patients is higher than...
113613,SA3,2019-20,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),All persons,Percentage of people who had the service (%),82.43,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600102,SA3,2020-21,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Physiotherapy,All persons,Total provider fees ($),1341737,NaN,NaN
600103,SA3,2020-21,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Podiatry,All persons,Total provider fees ($),1485522,NaN,NaN
600104,SA3,2020-21,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Practice Nurse/Aboriginal Health Worker,All persons,Total provider fees ($),3072378,NaN,NaN
600105,SA3,2020-21,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Psychiatry,All persons,Total provider fees ($),2939509,NaN,NaN
600106,SA3,2020-21,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 3,Speech Pathology,All persons,Total provider fees ($),58552,NaN,NaN

State Terriory had 6972 blanks because SA3 Group aggregages are not for a specific state or terriorty. They are showing aggregrates of each SA3 group by demographics and service.

SA3 groups:
004-01 = Major cities - higher SES
004-02 = Major cities - medium SES
004-03 = Major cities - lower SES
004-04 = Inner regional
004-05 = Outer regional
004-06 = Remote (incl. very remote)

In [99]:
# to ensure pivot table does not skip the blank stateterritory, filling in the blank cells.
df_mbs_201921_sa3_fill_na = df_mbs_201921_sa3.copy()
df_mbs_201921_sa3_fill_na['StateTerritory'].fillna('National-SA3Group', inplace=True)

In [100]:
print(df_mbs_201921_sa3_fill_na.isna().sum())
df_mbs_201921_sa3_fill_na.shape

Worksheet                  0
Year                       0
StateTerritory             0
GeographicUnit             0
GeographicCode             0
GeographicAreaName         0
GeographicGroup            0
ServiceLevel               0
Service                    0
DemographicGroup           0
MeasureName                0
MeasureValue               0
Flag                  372848
FlagExplanation       372848
dtype: int64

(400841, 14)

In [101]:
df_mbs_201921_sa3_fill_na[['StateTerritory','GeographicGroup']].value_counts()

StateTerritory     GeographicGroup
Qld                Major cities - medium SES     34860
NSW                Inner regional                30212
Vic                Major cities - medium SES     25564
                   Inner regional                24402
NSW                Major cities - higher SES     22078
                   Major cities - lower SES      20916
Qld                Inner regional                20916
NSW                Major cities - medium SES     18578
WA                 Major cities - medium SES     16268
Qld                Outer regional                13937
                   Major cities - higher SES     11620
Vic                Major cities - lower SES      10458
                   Major cities - higher SES     10458
Qld                Major cities - lower SES      10458
SA                 Major cities - medium SES     10451
Tas                Inner regional                 9289
NSW                Outer regional                 9282
SA                 Major cities - lower SES       8134
Tas                Outer regional                 8092
WA                 Remote (incl. very remote)     8071
ACT                Major cities - higher SES      6972
Vic                Outer regional                 5810
NT                 Remote (incl. very remote)     5782
SA                 Inner regional                 4648
                   Outer regional                 4648
WA                 Major cities - lower SES       4648
NT                 Outer regional                 4641
Qld                Remote (incl. very remote)     3486
WA                 Inner regional                 3486
                   Major cities - higher SES      3486
                   Outer regional                 3486
NSW                Remote (incl. very remote)     3220
Other Territories  Remote (incl. very remote)     2730
SA                 Major cities - higher SES      2324
ACT                Major cities - medium SES      2324
SA                 Remote (incl. very remote)     2324
ACT                Major cities - lower SES       1162
Other Territories  Inner regional                 1162
NSW                Ungrouped                      1162
National           National                       1162
National-SA3Group  Inner regional                 1162
                   Major cities - higher SES      1162
                   Major cities - lower SES       1162
                   Major cities - medium SES      1162
                   Outer regional                 1162
                   Remote (incl. very remote)     1162
ACT                Inner regional                 1162
dtype: int64

In [102]:
#grouping columns to check how many unique rows expected from pivot table. Expected 57263 rows
count_unique_rows = df_mbs_201921_sa3_fill_na.groupby(by=['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode', 'GeographicAreaName', 'GeographicGroup',
                               'ServiceLevel', 'Service', 'DemographicGroup'], as_index=False).agg({'MeasureValue' : 'count'})
count_unique_rows.shape

(57263, 11)

In [103]:
# Use pivot_table to reshape the DataFrame
df_mbs_201921_sa3_pivot = df_mbs_201921_sa3_fill_na.pivot_table(index=['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode', 
                                                           'GeographicAreaName', 'GeographicGroup', 'ServiceLevel', 'Service', 'DemographicGroup'],
                            columns='MeasureName', 
                            values='MeasureValue',
                            aggfunc='first')  # 'first' is used to pick the first value in case of duplicates

# Reset index to make the DataFrame flat
df_mbs_201921_sa3_pivot.reset_index(inplace=True)
df_mbs_201921_sa3_pivot.head(5)

MeasureName,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Medicare benefits per 100 people ($),No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid ($),Total provider fees ($)
0,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,3275.33,6314,14134,18.89,42.29,1094649,1612037
1,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,5036.77,8464,19537,27.12,62.6,1571825,2307710
2,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,5641.12,9429,18660,43.35,85.8,1226832,1605423
3,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,7827.74,8973,19925,61.57,136.71,1140815,1421204
4,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,4986.75,33180,72256,32.87,71.58,5034121,6946375

In [104]:
# count of rows, matches grouped dataframe. 57,363
df_mbs_201921_sa3_pivot.count()

MeasureName
Worksheet                                       57263
Year                                            57263
StateTerritory                                  57263
GeographicUnit                                  57263
GeographicCode                                  57263
GeographicAreaName                              57263
GeographicGroup                                 57263
ServiceLevel                                    57263
Service                                         57263
DemographicGroup                                57263
Medicare benefits per 100 people ($)            57263
No. of patients                                 57263
No. of services                                 57263
Percentage of people who had the service (%)    57263
Services per 100 people                         57263
Total Medicare benefits paid ($)                57263
Total provider fees ($)                         57263
dtype: int64

In [105]:
#removed the column index 'MeasureValue' to simply the table
df_mbs_201921_sa3_pivot.columns.name = None
df_mbs_201921_sa3_pivot.head()

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Medicare benefits per 100 people ($),No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid ($),Total provider fees ($)
0,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,3275.33,6314,14134,18.89,42.29,1094649,1612037
1,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,5036.77,8464,19537,27.12,62.6,1571825,2307710
2,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,5641.12,9429,18660,43.35,85.8,1226832,1605423
3,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,7827.74,8973,19925,61.57,136.71,1140815,1421204
4,SA3,2019-20,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,4986.75,33180,72256,32.87,71.58,5034121,6946375

In [106]:
df_mbs_201921_sa3_pivot.drop('Worksheet', inplace=True, axis=1)

In [107]:
df_mbs_201921_sa3_pivot.to_csv(os.path.join(path, 'clean_datasets/mbs_data/2019-21_phc_mbs.csv'))

## 3.MBS 2013-2019 Data Cleaning & Tranformation

In [108]:
# import the mbs data files and assign to a dataframe

#import required columns
filter_cols = ["Worksheet","Year","StateTerritory","GeographicUnit","GeographicCode","GeographicAreaName","GeographicGroup", "ServiceLevel", "Service", "DemographicGroup","MeasureName","MeasureValue","Flag","FlagExplanation"]

df_mbs_201319 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2013-2019/AIHW_MBS_1314_1819_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)
df_mbs_201319.head(3)

/var/folders/6w/mdyngzzd2_z7brmk404qky_m0000gs/T/ipykernel_70532/3792998903.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mbs_201319 = pd.read_csv(os.path.join(path, 'original_datasets/mbs_data/phc-mbs-2013-2019/AIHW_MBS_1314_1819_CSV.csv'), encoding='ISO-8859-1', usecols=filter_cols, index_col=None)

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
0,PHN,2018-19,NAT,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Percentage of people who had the service (%),86.05,NaN,NaN
1,PHN,2018-19,NAT,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Services per 100 people,434.16,NaN,NaN
2,PHN,2018-19,NAT,NAT,001NAT,National,National,Level 1,GP attendances (total),0-14,Medicare benefits per 100 people ($),19920.00,NaN,NaN

In [109]:
df_mbs_201319.shape

(1850655, 14)

In [110]:
# check the worksheet names to find SA3 reference
df_mbs_201319['Worksheet'].unique()

array(['PHN', 'SA3', 'PHN - Age standardised', 'PHN - GP aged care',
       'Private health insurance'], dtype=object)

#### 3.1 Extract and Transform SA3 Worksheet Data

In [111]:
df_mbs_201319_sa3 = df_mbs_201319[df_mbs_201319['Worksheet']== 'SA3'].copy()
df_mbs_201319_sa3.shape

(1206156, 14)

In [112]:
df_mbs_201319_sa3.isnull().sum()

Worksheet                   0
Year                        0
StateTerritory          20916
GeographicUnit              0
GeographicCode              0
GeographicAreaName          0
GeographicGroup             0
ServiceLevel                0
Service                     0
DemographicGroup            0
MeasureName                 0
MeasureValue           128534
Flag                  1076623
FlagExplanation       1076623
dtype: int64

20,916 values are missing for StateTerritory. 
128534 values are missing for MeasureValue.

3.1.1 Fill in missing values

In [113]:
df_mbs_201319_sa3[df_mbs_201319_sa3['StateTerritory'].isnull()]

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
113526,SA3,2018-19,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Percentage of people who had the service (%),74.21,NaN,NaN
113527,SA3,2018-19,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Services per 100 people,368.97,NaN,NaN
113528,SA3,2018-19,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,Medicare benefits per 100 people ($),17465.00,NaN,NaN
113529,SA3,2018-19,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,No. of patients,934016.00,NaN,NaN
113530,SA3,2018-19,NaN,SA3,004-01,Major cities - higher SES,Major cities - higher SES,Level 1,GP attendances (total),0-24,No. of services,4643823.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827194,SA3,2013-14,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 1,Specialist attendances (total),Males,Medicare benefits per 100 people ($),2459.00,NaN,NaN
1827195,SA3,2013-14,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 1,Specialist attendances (total),Males,No. of patients,43360.00,NaN,NaN
1827196,SA3,2013-14,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 1,Specialist attendances (total),Males,No. of services,93787.00,NaN,NaN
1827197,SA3,2013-14,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 1,Specialist attendances (total),Males,Total Medicare benefits paid ($),7311731.00,NaN,NaN
1827198,SA3,2013-14,NaN,SA3,004-06,Remote (incl. very remote),Remote (incl. very remote),Level 1,Specialist attendances (total),Males,Total provider fees ($),9871635.00,NaN,NaN

In [114]:
# to ensure pivot table does not skip the blank stateterritory, filling in the blank cells.
df_mbs_201319_sa3_fill_na = df_mbs_201319_sa3.copy()
df_mbs_201319_sa3_fill_na['StateTerritory'].fillna('National-SA3Group', inplace=True)

In [115]:
# checking for nulls in StateTerritory
print(df_mbs_201319_sa3_fill_na.isna().sum())
df_mbs_201319_sa3_fill_na.shape

Worksheet                   0
Year                        0
StateTerritory              0
GeographicUnit              0
GeographicCode              0
GeographicAreaName          0
GeographicGroup             0
ServiceLevel                0
Service                     0
DemographicGroup            0
MeasureName                 0
MeasureValue           128534
Flag                  1076623
FlagExplanation       1076623
dtype: int64

(1206156, 14)

In [116]:
# Fill in missing value so the lines are not removed by the pivot. Assigning value 'n.p' for 'Not Published'
df_mbs_201319_sa3_fill_na['MeasureValue'].fillna('n.p', inplace=True)

In [117]:
#checking for nulls in MeasureValue column
df_mbs_201319_sa3_fill_na.isna().sum()

Worksheet                   0
Year                        0
StateTerritory              0
GeographicUnit              0
GeographicCode              0
GeographicAreaName          0
GeographicGroup             0
ServiceLevel                0
Service                     0
DemographicGroup            0
MeasureName                 0
MeasureValue                0
Flag                  1076623
FlagExplanation       1076623
dtype: int64

In [118]:
#checking specific data for investigation (step can be ignored)
df_mbs_201319_sa3_fill_na[(df_mbs_201319_sa3_fill_na['Year'] == '2015-16') & (df_mbs_201319_sa3_fill_na['GeographicCode']=='30204') & 
                        (df_mbs_201319_sa3_fill_na['Service']=='GP Mental Health') & (df_mbs_201319_sa3_fill_na['DemographicGroup']== 'All persons')]

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureName,MeasureValue,Flag,FlagExplanation
1343485,SA3,2015-16,Qld,SA3,30204,Sandgate,Major cities - medium SES,Level 3,GP Mental Health,All persons,Percentage of people who had the service (%),7.3,NaN,NaN
1343486,SA3,2015-16,Qld,SA3,30204,Sandgate,Major cities - medium SES,Level 3,GP Mental Health,All persons,Services per 100 people,13.31,NaN,NaN
1343487,SA3,2015-16,Qld,SA3,30204,Sandgate,Major cities - medium SES,Level 3,GP Mental Health,All persons,Medicare benefits per 100 people ($),1081.0,NaN,NaN

In [119]:
#checking specific data for investigation (step can be ignored)
df_mbs_201319_sa3_fill_na[(df_mbs_201319_sa3_fill_na['MeasureName'] == 'No. of services') 
                          & (df_mbs_201319_sa3_fill_na['MeasureValue'] == '7852')]

Empty DataFrame
Columns: [Worksheet, Year, StateTerritory, GeographicUnit, GeographicCode, GeographicAreaName, GeographicGroup, ServiceLevel, Service, DemographicGroup, MeasureName, MeasureValue, Flag, FlagExplanation]
Index: []

In [120]:
#grouping columns to check how many unique rows expected from pivot table. Expected 172323 rows
count_unique_rows_2 = df_mbs_201319_sa3_fill_na.groupby(by=['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode', 'GeographicAreaName', 'GeographicGroup',
                               'ServiceLevel', 'Service', 'DemographicGroup'], as_index=False).agg({'MeasureValue' : 'count'})
count_unique_rows_2

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureValue
0,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,7
1,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,7
2,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,7
3,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,7
4,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,7
...,...,...,...,...,...,...,...,...,...,...,...
172318,SA3,2018-19,WA,SA3,51104,Mid West,Remote (incl. very remote),Level 3,Physiotherapy,All persons,7
172319,SA3,2018-19,WA,SA3,51104,Mid West,Remote (incl. very remote),Level 3,Podiatry,All persons,7
172320,SA3,2018-19,WA,SA3,51104,Mid West,Remote (incl. very remote),Level 3,Practice Nurse/Aboriginal Health Worker,All persons,7
172321,SA3,2018-19,WA,SA3,51104,Mid West,Remote (incl. very remote),Level 3,Psychiatry,All persons,7
172322,SA3,2018-19,WA,SA3,51104,Mid West,Remote (incl. very remote),Level 3,Speech Pathology,All persons,7

In [121]:
#creatiing unique key by combining columns.  This is to compare missing key with pivot table
count_unique_rows_2['key'] = count_unique_rows_2['Worksheet'].astype(str) + count_unique_rows_2['Year'].astype(str) + count_unique_rows_2['StateTerritory'].astype(str) + count_unique_rows_2['GeographicUnit'].astype(str) + count_unique_rows_2['GeographicCode'].astype(str) + count_unique_rows_2['GeographicAreaName'].astype(str) + count_unique_rows_2['GeographicGroup'].astype(str) + count_unique_rows_2['ServiceLevel'].astype(str) + count_unique_rows_2['Service'].astype(str) + count_unique_rows_2['DemographicGroup'].astype(str)
count_unique_rows_2['key']

0         SA32013-14ACTSA380101BelconnenMajor cities - m...
1         SA32013-14ACTSA380101BelconnenMajor cities - m...
2         SA32013-14ACTSA380101BelconnenMajor cities - m...
3         SA32013-14ACTSA380101BelconnenMajor cities - m...
4         SA32013-14ACTSA380101BelconnenMajor cities - m...
                                ...
172318    SA32018-19WASA351104Mid WestRemote (incl. very...
172319    SA32018-19WASA351104Mid WestRemote (incl. very...
172320    SA32018-19WASA351104Mid WestRemote (incl. very...
172321    SA32018-19WASA351104Mid WestRemote (incl. very...
172322    SA32018-19WASA351104Mid WestRemote (incl. very...
Name: key, Length: 172323, dtype: object

In [122]:
# investigating why 2 rows are generated for these 15 rows by pivotable and grouping
dups = ["SA32013-14VicSA321502MilduraOuter regionalLevel 1Allied Health attendances (total)45-64", "SA32014-15VicSA320401Upper Goulburn ValleyInner regionalLevel 3GP Mental HealthAll persons", "SA32014-15VicSA321704WarrnamboolInner regionalLevel 1Nursing and Aboriginal Health Workers (total)65+",
        "SA32015-16QldSA330204SandgateMajor cities - medium SESLevel 3GP Mental HealthAll persons",
        "SA32015-16QldSA331402North LakesMajor cities - medium SESLevel 1Nursing and Aboriginal Health Workers (total)65+",
        "SA32016-17NSWSA310106Young - YassInner regionalLevel 1Nursing and Aboriginal Health Workers (total)All persons",
        "SA32016-17NSWSA311903HurstvilleMajor cities - medium SESLevel 1Allied Health attendances (total)65+",
        "SA32016-17QldSA330402Kenmore - Brookfield - MoggillMajor cities - higher SESLevel 2Allied Health subtotal - OptometryAll persons",
        "SA32016-17QldSA331605NoosaMajor cities - medium SESLevel 3GP Mental HealthAll persons",
        "SA32017-18NSWSA310402Coffs HarbourInner regionalLevel 3GP Multidisciplinary Case ConferenceAll persons",
        "SA32017-18NSWSA312103Ku-ring-gaiMajor cities - higher SESLevel 1Nursing and Aboriginal Health Workers (total)All persons",
        "SA32017-18QldSA330601Cairns - NorthOuter regionalLevel 3Cervical Smear PIPAll persons",
        "SA32017-18QldSA331902BurnettInner regionalLevel 2Allied Health subtotal - OptometryAll persons",
        "SA32018-19NSWSA310801Great LakesInner regionalLevel 1Allied Health attendances (total)45-64",
        "SA32018-19TasSA360105Hobart InnerInner regionalLevel 1Allied Health attendances (total)45-64"]
x = count_unique_rows_2['key'].isin(['SA32013-14VicSA321502MilduraOuter regionalLevel 1Allied Health attendances (total)45-64'])
count_unique_rows_2[x]

,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,MeasureValue,key
25081,SA3,2013-14,Vic,SA3,21502,Mildura,Outer regional,Level 1,Allied Health attendances (total),45-64,1,SA32013-14VicSA321502MilduraOuter regionalLeve...
25253,SA3,2013-14,Vic,SA3,21502,Mildura,Outer regional,Level 1,Allied Health attendances (total),45-64,6,SA32013-14VicSA321502MilduraOuter regionalLeve...

##### 3.1.2 Pivot MBS data by Measure Name / Value

In [123]:
# Use pivot_table to reshape the DataFrame
df_mbs_201319_sa3_pivot = df_mbs_201319_sa3_fill_na.pivot_table(index=['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode', 
                                                           'GeographicAreaName', 'GeographicGroup', 'ServiceLevel', 'Service', 'DemographicGroup'],
                            columns='MeasureName', 
                            values='MeasureValue',
                            aggfunc='first')  # 'first' is used to pick the first value in case of duplicates

# Reset index to make the DataFrame flat
df_mbs_201319_sa3_pivot.reset_index(inplace=True)
df_mbs_201319_sa3_pivot.head(5)

MeasureName,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Medicare benefits per 100 people ($),No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid ($),Total provider fees ($)
0,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),0-24,2576.0,5624.0,10879.0,17.27,33.41,838549.0,1026474.0
1,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),25-44,4004.0,7714.0,15870.0,24.75,50.93,1247656.0,1600846.0
2,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),45-64,4672.0,8998.0,15754.0,41.32,72.35,1017264.0,1197133.0
3,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,5819.0,6397.0,12316.0,55.07,106.01,675946.0,761837.0
4,SA3,2013-14,ACT,SA3,80101,Belconnen,Major cities - medium SES,Level 1,Allied Health attendances (total),All persons,3892.0,28733.0,54818.0,29.59,56.45,3779415.0,4586290.0

In [124]:
# count of rows, matches grouped dataframe. 172,323
df_mbs_201319_sa3_pivot.shape

(172323, 17)

In [125]:
df_mbs_201319_sa3_pivot['key'] = df_mbs_201319_sa3_pivot['Worksheet'].astype(str) + df_mbs_201319_sa3_pivot['Year'].astype(str) + df_mbs_201319_sa3_pivot['StateTerritory'].astype(str) + df_mbs_201319_sa3_pivot['GeographicUnit'].astype(str) + df_mbs_201319_sa3_pivot['GeographicCode'].astype(str) + df_mbs_201319_sa3_pivot['GeographicAreaName'].astype(str) + df_mbs_201319_sa3_pivot['GeographicGroup'].astype(str) + df_mbs_201319_sa3_pivot['ServiceLevel'].astype(str) + df_mbs_201319_sa3_pivot['Service'].astype(str) + df_mbs_201319_sa3_pivot['DemographicGroup'].astype(str)
df_mbs_201319_sa3_pivot['key'].value_counts

<bound method IndexOpsMixin.value_counts of 0         SA32013-14ACTSA380101BelconnenMajor cities - m...
1         SA32013-14ACTSA380101BelconnenMajor cities - m...
2         SA32013-14ACTSA380101BelconnenMajor cities - m...
3         SA32013-14ACTSA380101BelconnenMajor cities - m...
4         SA32013-14ACTSA380101BelconnenMajor cities - m...
                                ...
172318    SA32018-19WASA351104Mid WestRemote (incl. very...
172319    SA32018-19WASA351104Mid WestRemote (incl. very...
172320    SA32018-19WASA351104Mid WestRemote (incl. very...
172321    SA32018-19WASA351104Mid WestRemote (incl. very...
172322    SA32018-19WASA351104Mid WestRemote (incl. very...
Name: key, Length: 172323, dtype: object>

In [126]:
df_mbs_201319_sa3_pivot.isna().sum()

MeasureName
Worksheet                                        0
Year                                             0
StateTerritory                                   0
GeographicUnit                                   0
GeographicCode                                   0
GeographicAreaName                               0
GeographicGroup                                  0
ServiceLevel                                     0
Service                                          0
DemographicGroup                                 0
Medicare benefits per 100 people ($)            15
No. of patients                                 15
No. of services                                 15
Percentage of people who had the service (%)    15
Services per 100 people                         15
Total Medicare benefits paid ($)                15
Total provider fees ($)                         15
key                                              0
dtype: int64

In [127]:
df_mbs_201319_sa3_pivot[df_mbs_201319_sa3_pivot.isna().any(axis=1)]

MeasureName,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Medicare benefits per 100 people ($),No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid ($),Total provider fees ($),key
25081,SA3,2013-14,Vic,SA3,21502,Mildura,Outer regional,Level 1,Allied Health attendances (total),45-64,NaN,NaN,NaN,38.91,NaN,NaN,NaN,SA32013-14VicSA321502MilduraOuter regionalLeve...
25253,SA3,2013-14,Vic,SA3,21502,Mildura,Outer regional,Level 1,Allied Health attendances (total),45-64,4372.0,5339.0,10435.0,NaN,76.05,599872.0,650466.0,SA32013-14VicSA321502MilduraOuter regionalLeve...
49168,SA3,2014-15,Vic,SA3,20401,Upper Goulburn Valley,Inner regional,Level 3,GP Mental Health,All persons,1038.0,3962.0,6514.0,NaN,12.32,548838.0,560380.0,SA32014-15VicSA320401Upper Goulburn ValleyInne...
53772,SA3,2014-15,Vic,SA3,21704,Warrnambool,Inner regional,Level 1,Nursing and Aboriginal Health Workers (total),65+,NaN,NaN,NaN,14.05,32.5,NaN,NaN,SA32014-15VicSA321704WarrnamboolInner regional...
54595,SA3,2014-15,Vic,SA3,20401,Upper Goulburn Valley,Inner regional,Level 3,GP Mental Health,All persons,NaN,NaN,NaN,7.49,NaN,NaN,NaN,SA32014-15VicSA320401Upper Goulburn ValleyInne...
54604,SA3,2014-15,Vic,SA3,21704,Warrnambool,Inner regional,Level 1,Nursing and Aboriginal Health Workers (total),65+,412.0,1210.0,2798.0,NaN,NaN,35480.0,35480.0,SA32014-15VicSA321704WarrnamboolInner regional...
67513,SA3,2015-16,Qld,SA3,30204,Sandgate,Major cities - medium SES,Level 3,GP Mental Health,All persons,NaN,4306.0,7852.0,NaN,NaN,638032.0,670041.0,SA32015-16QldSA330204SandgateMajor cities - me...
72117,SA3,2015-16,Qld,SA3,31402,North Lakes,Major cities - medium SES,Level 1,Nursing and Aboriginal Health Workers (total),65+,726.0,1152.0,NaN,17.44,38.34,NaN,NaN,SA32015-16QldSA331402North LakesMajor cities -...
72691,SA3,2015-16,Qld,SA3,30204,Sandgate,Major cities - medium SES,Level 3,GP Mental Health,All persons,1081.0,NaN,NaN,7.3,13.31,NaN,NaN,SA32015-16QldSA330204SandgateMajor cities - me...
72700,SA3,2015-16,Qld,SA3,31402,North Lakes,Major cities - medium SES,Level 1,Nursing and Aboriginal Health Workers (total),65+,NaN,NaN,2533.0,NaN,NaN,47931.0,47954.0,SA32015-16QldSA331402North LakesMajor cities -...
86989,SA3,2016-17,NSW,SA3,10106,Young - Yass,Inner regional,Level 1,Nursing and Aboriginal Health Workers (total),All persons,77.0,765.0,1311.0,NaN,3.58,28102.0,28232.0,SA32016-17NSWSA310106Young - YassInner regiona...
91652,SA3,2016-17,NSW,SA3,11903,Hurstville,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,NaN,NaN,NaN,61.62,183.29,NaN,NaN,SA32016-17NSWSA311903HurstvilleMajor cities - ...
92028,SA3,2016-17,NSW,SA3,10106,Young - Yass,Inner regional,Level 1,Nursing and Aboriginal Health Workers (total),All persons,NaN,NaN,NaN,2.09,NaN,NaN,NaN,SA32016-17NSWSA310106Young - YassInner regiona...
92075,SA3,2016-17,NSW,SA3,11903,Hurstville,Major cities - medium SES,Level 1,Allied Health attendances (total),65+,9739.0,12612.0,37518.0,NaN,NaN,1993532.0,2096630.0,SA32016-17NSWSA311903HurstvilleMajor cities - ...
96239,SA3,2016-17,Qld,SA3,30402,Kenmore - Brookfield - Moggill,Major cities - higher SES,Level 2,Allied Health subtotal - Optometry,All persons,NaN,NaN,22114.0,NaN,NaN,988538.0,1049503.0,SA32016-17QldSA330402Kenmore - Brookfield - Mo...
100877,SA3,2016-17,Qld,SA3,31605,Noosa,Major cities - medium SES,Level 3,GP Mental Health,All persons,1285.0,4055.0,6763.0,9.52,15.88,NaN,NaN,SA32016-17QldSA331605NoosaMajor cities - mediu...
102049,SA3,2016-17,Qld,SA3,30402,Kenmore - Brookfield - Moggill,Major cities - higher SES,Level 2,Allied Health subtotal - Optometry,All persons,2090.0,16659.0,NaN,35.21,46.74,NaN,NaN,SA32016-17QldSA330402Kenmore - Brookfield - Mo...
102084,SA3,2016-17,Qld,SA3,31605,Noosa,Major cities - medium SES,Level 3,GP Mental Health,All persons,NaN,NaN,NaN,NaN,NaN,547246.0,557988.0,SA32016-17QldSA331605NoosaMajor cities - mediu...
115742,SA3,2017-18,NSW,SA3,10402,Coffs Harbour,Inner regional,Level 3,GP Multidisciplinary Case Conference,All persons,93.0,531.0,769.0,NaN,NaN,82843.0,82843.0,SA32017-18NSWSA310402Coffs HarbourInner region...
120346,SA3,2017-18,NSW,SA3,12103,Ku-ring-gai,Major cities - higher SES,Level 1,Nursing and Aboriginal Health Workers (total),All persons,75.0,NaN,NaN,2.66,5.04,NaN,NaN,SA32017-18NSWSA312103Ku-ring-gaiMajor cities -...
121419,SA3,2017-18,NSW,SA3,10402,Coffs Harbour,Inner regional,Level 3,GP Multidisciplinary Case Conference,All persons,NaN,NaN,NaN,0.6,0.87,NaN,NaN,SA32017-18NSWSA310402Coffs HarbourInner region...
121428,SA3,2017-18,NSW,SA3,12103,Ku-ring-gai,Major cities - higher SES,Level 1,Nursing and Aboriginal Health Workers (total),All persons,NaN,3319.0,6284.0,NaN,NaN,93252.0,104078.0,SA32017-18NSWSA312103Ku-ring-gaiMajor cities -...
124948,SA3,2017-18,Qld,SA3,30601,Cairns - North,Outer regional,Level 3,Cervical Smear PIP,All persons,NaN,NaN,NaN,NaN,NaN,8317.0,9446.0,SA32017-18QldSA330601Cairns - NorthOuter regio...
129604,SA3,2017-18,Qld,SA3,31902,Burnett,Inner regional,Level 2,Allied Health subtotal - Optometry,All persons,1887.0,14261.0,19659.0,28.66,39.51,938599.0,NaN,SA32017-18QldSA331902BurnettInner regionalLeve...
131374,SA3,2017-18,Qld,SA3,30601,Cairns - North,Outer regional,Level 3,Cervical Smear PIP,All persons,15.0,148.0,148.0,0.27,0.27,NaN,NaN,SA32017-18QldSA330601Cairns - NorthOuter regio...
131441,SA3,2017-18,Qld,SA3,31902,Burnett,Inner regional,Level 2,Allied Health subtotal - Optometry,All persons,NaN,NaN,NaN,NaN,NaN,NaN,962622.0,SA32017-18QldSA331902BurnettInner regionalLeve...
144433,SA3,2018-19,NSW,SA3,10801,Great Lakes,Inner regional,Level 1,Allied Health attendances (total),45-64,NaN,NaN,9409.0,NaN,NaN,556240.0,621370.0,SA32018-19NSWSA310801Great LakesInner regional...
152055,SA3,2018-19,NSW,SA3,10801,Great Lakes,Inner regional,Level 1,Allied Health attendances (total),45-64,6192.0,3899.0,NaN,43.41,104.74,NaN,NaN,SA32018-19NSWSA310801Great LakesInner regional...
163111,SA3,2018-19,Tas,SA3,60105,Hobart Inner,Inner regional,Level 1,Allied Health attendances (total),45-64,NaN,NaN,NaN,50.57,108.6,NaN,NaN,SA32018-19TasSA360105Hobart InnerInner regiona...
163126,SA3,2018-19,Tas,SA3,60105,Hobart Inner,Inner regional,Level 1,Allied Health attendances (total),45-64,7449.0,6670.0,14324.0,NaN,NaN,982535.0,1192474.0,SA32018-19TasSA360105Hobart InnerInner regiona...

In [128]:
df_mbs_201319_sa3_pivot[df_mbs_201319_sa3_pivot.duplicated(subset=['key'], keep='first')]['key'].to_clipboard()

In [129]:
df_mbs_201319_sa3_pivot[(df_mbs_201319_sa3_pivot['Year'] == '2015-16') & (df_mbs_201319_sa3_pivot['GeographicCode']=='30204') & 
                        (df_mbs_201319_sa3_pivot['Service']=='GP Mental Health') & (df_mbs_201319_sa3_pivot['DemographicGroup']== 'All persons')]

MeasureName,Worksheet,Year,StateTerritory,GeographicUnit,GeographicCode,GeographicAreaName,GeographicGroup,ServiceLevel,Service,DemographicGroup,Medicare benefits per 100 people ($),No. of patients,No. of services,Percentage of people who had the service (%),Services per 100 people,Total Medicare benefits paid ($),Total provider fees ($),key
72691,SA3,2015-16,Qld,SA3,30204,Sandgate,Major cities - medium SES,Level 3,GP Mental Health,All persons,1081.0,NaN,NaN,7.3,13.31,NaN,NaN,SA32015-16QldSA330204SandgateMajor cities - me...

In [130]:
missing_keys = count_unique_rows_2[~count_unique_rows_2['key'].isin(df_mbs_201319_sa3_pivot['key'])]

In [131]:
missing_keys.shape

(0, 12)

In [132]:
df_mbs_201319_sa3_pivot.columns

Index(['Worksheet', 'Year', 'StateTerritory', 'GeographicUnit',
       'GeographicCode', 'GeographicAreaName', 'GeographicGroup',
       'ServiceLevel', 'Service', 'DemographicGroup',
       'Medicare benefits per 100 people ($)', 'No. of patients',
       'No. of services', 'Percentage of people who had the service (%)',
       'Services per 100 people', 'Total Medicare benefits paid ($)',
       'Total provider fees ($)', 'key'],
      dtype='object', name='MeasureName')

In [133]:
# Column key will be dropped. Was generated for investigation purposes
df_mbs_201319_sa3_pivot.drop(['key', 'Worksheet'], axis=1, inplace=True)
df_mbs_201319_sa3_pivot.columns

Index(['Year', 'StateTerritory', 'GeographicUnit', 'GeographicCode',
       'GeographicAreaName', 'GeographicGroup', 'ServiceLevel', 'Service',
       'DemographicGroup', 'Medicare benefits per 100 people ($)',
       'No. of patients', 'No. of services',
       'Percentage of people who had the service (%)',
       'Services per 100 people', 'Total Medicare benefits paid ($)',
       'Total provider fees ($)'],
      dtype='object', name='MeasureName')

In [134]:
df_mbs_201319_sa3_pivot.to_csv(os.path.join(path, 'clean_datasets/mbs_data/2013-19_phc_mbs.csv'))